export const S = {
  app: {
    minHeight: '100vh',
    background: '#020817',
    color: '#f8fafc',
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
  },
  container: {
    maxWidth: 480,
    margin: '0 auto',
    paddingBottom: 80,
    paddingLeft: 16,
    paddingRight: 16,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 20,
    paddingBottom: 16,
  },
  logo: {
    background: 'linear-gradient(135deg, #22c55e, #facc15)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    fontWeight: 900,
    fontSize: 28,
    letterSpacing: '0.1em',
    fontFamily: "'DM Mono', monospace",
    lineHeight: 1,
  },
  logoSub: {
    fontSize: 9,
    letterSpacing: '0.15em',
    color: '#475569',
    fontWeight: 600,
    textTransform: 'uppercase',
    marginTop: 2,
  },
  btnPrimary: {
    background: 'linear-gradient(135deg, #22c55e, #16a34a)',
    color: '#020817',
    border: 'none',
    borderRadius: 8,
    padding: '8px 14px',
    fontWeight: 700,
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: '0.02em',
  },
  btnGhost: {
    background: 'transparent',
    color: '#94a3b8',
    border: '1px solid #1e293b',
    borderRadius: 8,
    padding: '8px 14px',
    fontWeight: 600,
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: "'DM Sans', sans-serif",
  },
  btnBlue: {
    background: 'rgba(96,165,250,0.15)',
    color: '#60a5fa',
    border: '1px solid rgba(96,165,250,0.3)',
    borderRadius: 6,
    padding: '4px 10px',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
  },
  btnGreen: {
    background: 'rgba(34,197,94,0.15)',
    color: '#22c55e',
    border: '1px solid rgba(34,197,94,0.3)',
    borderRadius: 6,
    padding: '4px 10px',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
  },
  card: {
    background: '#0f172a',
    border: '1px solid #1e293b',
    borderRadius: 12,
    padding: 14,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.12em',
    color: '#475569',
    textTransform: 'uppercase',
    marginBottom: 10,
    marginTop: 20,
  },
}
